Repository metadew/iesi, pull requests merged in 2020-08, with the labels that each got.

#190 Scripts endpoint sorting by name
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/dto/ScriptDtoRepository.java
  core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/script/ScriptControllerTest.java
  core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/script/dto/ScriptDtoServiceTest.java
Labels: REST Server, enhancement

#192 IESI-Core replace deprecated API calls
  core/java/iesi-core/pom.xml
  core/java/iesi-core/src/main/java/io/metadew/iesi/connection/operation/ConnectionOperation.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/fwk/FwkRoute.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/wfa/WfaExecuteFilePing.java
  core/java/iesi-core/src/test/java/io/metadew/iesi/datatypes/text/TextServiceTest.java
Labels: bug

#187 Add run id to API response for ScriptExecutionRequest
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/configuration/execution/ExecutionRequestLabelConfiguration.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/definition/execution/AuthenticatedExecutionRequest.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/definition/execution/ExecutionRequest.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/definition/execution/ExecutionRequestBuilder.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/definition/execution/ExecutionRequestLabel.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/definition/execution/NonAuthenticatedExecutionRequest.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/definition/execution/key/ExecutionRequestKey.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/definition/execution/key/ExecutionRequestLabelKey.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/definition/execution/script/ScriptExecution.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/definition/execution/script/ScriptExecutionRequest.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/definition/execution/script/ScriptExecutionRequestImpersonation.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/definition/execution/script/ScriptExecutionRequestParameter.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/definition/execution/script/ScriptNameExecutionRequest.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/definition/execution/script/key/ScriptExecutionKey.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/definition/execution/script/key/ScriptExecutionRequestImpersonationKey.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/definition/execution/script/key/ScriptExecutionRequestKey.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/definition/execution/script/key/ScriptExecutionRequestParameterKey.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/definition/impersonation/key/ImpersonationKey.java
  core/java/iesi-core/src/main/resources/application-repository.yml
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/ExecutionRequestController.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/ExecutionRequestDtoRepository.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/ExecutionRequestService.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/IExecutionRequestDtoRepository.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/IExecutionRequestService.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/dto/ExecutionRequestDto.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/dto/ExecutionRequestDtoModelAssembler.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/dto/ExecutionRequestDtoRepository.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/dto/ExecutionRequestLabelDto.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/script/dto/ScriptExecutionRequestDto.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/script/dto/ScriptExecutionRequestDtoModelAssembler.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/script/dto/ScriptExecutionRequestImpersonationDto.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/script/dto/ScriptExecutionRequestParameterDto.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/impersonation/dto/ImpersonationDto.java
  core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/executionrequest/ExecutionRequestControllerTest.java
  core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/executionrequest/ExecutionRequestRepositoryDtoTest.java
  core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/executionrequest/ExecutionRequestServiceTest.java
  core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/executionrequest/script/dto/ScriptExecutionRequestDtoTest.java
  core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/scriptResultDto/ScriptResultServiceTest.java
  core/java/iesi-rest-without-microservices/src/test/resources/application-iesi-repository.yml
Labels: enhancement

#188 Add pagination to fetch all Execution Requests endpoint
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/ExecutionRequestController.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/ExecutionRequestDtoRepository.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/ExecutionRequestService.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/IExecutionRequestDtoRepository.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/IExecutionRequestService.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/dto/ExecutionRequestDtoModelAssembler.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/dto/IExecutionRequestDtoRepository.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/pagination/TotalPages.java
  core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/executionrequest/ExecutionRequestControllerTest.java
  core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/executionrequest/ExecutionRequestRepositoryDtoTest.java
  core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/script/dto/ScriptDtoServiceTest.java
  core/java/iesi-rest-without-microservices/src/test/resources/application-iesi-repository.yml
Labels: enhancement

#191 scripts endpoint filter by name and label key/value
  core/java/iesi-core/src/main/java/io/metadew/iesi/connection/database/connection/DatabaseConnectionService.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/ScriptController.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/ScriptFilter.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/ScriptFilterOption.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/dto/IScriptDtoRepository.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/dto/IScriptDtoService.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/dto/ScriptDto.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/dto/ScriptDtoModelAssembler.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/dto/ScriptDtoRepository.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/dto/ScriptDtoService.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/dto/action/ActionDto.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/dto/action/ScriptActionDtoService.java
  core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/builder/script/ScriptDtoBuilder.java
  core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/script/ScriptControllerTest.java
  core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/script/dto/ScriptDtoRepositoryTest.java
  core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/script/dto/ScriptDtoServiceTest.java
Labels: REST Server, enhancement

#196 Allow sort by script name, script version and request timestamp for execution requests
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/ExecutionRequestController.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/ExecutionRequestDtoRepository.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/ExecutionRequestFilter.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/ExecutionRequestFilterOption.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/ExecutionRequestService.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/IExecutionRequestDtoRepository.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/IExecutionRequestService.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/dto/ExecutionRequestDto.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/dto/ExecutionRequestDtoModelAssembler.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/helper/PaginatedRepository.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/dto/ScriptDtoRepository.java
  core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/executionrequest/ExecutionRequestControllerTest.java
  core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/executionrequest/ExecutionRequestRepositoryDtoTest.java
  core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/script/dto/ScriptDtoServiceTest.java
Labels: enhancement

#194 Allow Arrays to be stored in the local cache
  core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/ExecutionRuntime.java
Labels: enhancement

#197 Convert limit specific SQL language for Oracle
  core/java/iesi-core/src/main/java/io/metadew/iesi/connection/database/connection/DatabaseConnectionService.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/connection/database/connection/IDatabaseConnectionService.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/connection/database/db2/Db2DatabaseConnectionService.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/connection/database/dremio/DremioDatabaseConnectionService.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/connection/database/drill/DrillDatabaseConnectionService.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/connection/database/mariadb/MariadbDatabaseConnectionService.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/connection/database/mssql/MssqlDatabaseConnectionService.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/connection/database/mysql/MysqlDatabaseConnectionService.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/connection/database/oracle/OracleDatabaseConnectionService.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/connection/database/sqlite/SqliteDatabaseConnectionService.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/connection/database/temporary/TemporaryDatabaseConnectionServiceImpl.java
  core/java/iesi-core/src/test/java/io/metadew/iesi/common/configuration/ConfigurationTest.java
  core/java/iesi-core/src/test/java/io/metadew/iesi/connection/database/OracleDatabaseConnectionServiceTest.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/dto/ScriptDtoRepository.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/dto/ScriptDtoService.java
  core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/configuration/TestConfiguration.java
Labels: enhancement

#88 Split IESI action and actual operation time measurement
  core/java/iesi-core/src/main/java/io/metadew/iesi/datatypes/template/TemplateService.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/datatypes/text/TextService.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/configuration/template/TemplateConfiguration.java
  core/java/iesi-core/test
Labels: enhancement

#209 Provide logical messages for authentication errors on API
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/configuration/security/jwt/ApiError.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/configuration/security/jwt/JWTAuthenticationFilter.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/configuration/security/jwt/JwtService.java
  core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/configuration/security/jwt/JWTAuthenticationFilterTest.java
  core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/script/ScriptControllerTest.java
Labels: enhancement
