Repository metadew/iesi, pull requests merged in 2020-11, with the labels that each got.

#250 CORS error for PUT and DELETE endpoints
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/actiontypes/ActionTypeController.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/component/ComponentsController.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/configuration/security/disabled/DisabledWebSecurityConfiguration.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/configuration/security/jwt/JwtWebSecurityConfiguration.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/connection/ConnectionsController.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/connectiontypes/ConnectionTypeController.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/environment/EnvironmentsController.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/ExecutionRequestController.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/impersonation/ImpersonationController.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/ScriptController.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/scriptExecutionDto/ScriptExecutionDtoController.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/scriptResultDto/ScriptResultController.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/user/UserController.java
Labels: bug

#245 allow only defining begin index for text.substring
  core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/data/text/TextSubstring.java
  core/java/iesi-core/src/test/java/io/metadew/iesi/script/execution/instruction/data/text/TextSubstringTest.java
Labels: enhancement

#247 Allow time.format to receive 3 parameters like date.format
  core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/data/time/TimeFormat.java
  core/java/iesi-core/src/test/java/io/metadew/iesi/script/execution/instruction/data/time/TimeFormatTest.java
Labels: bug

#246 Allow download of script configuration from API
  core/java/iesi-rest-without-microservices/docs/iesi-openapi.yaml
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/ScriptController.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/dto/ScriptDto.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/dto/version/ScriptVersionDto.java
  core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/script/ScriptControllerTest.java
Labels: enhancement, ready

#256 http.executeRequest should update output dataset for override
  core/java/iesi-core/src/main/java/io/metadew/iesi/connection/tools/FolderTools.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/datatypes/dataset/keyvalue/KeyValueDatasetService.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/http/HttpExecuteRequest.java
  core/java/iesi-core/src/main/resources/application-repository.yml
  core/java/iesi-core/src/main/resources/application.yml
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/configuration/security/disabled/DisabledWebSecurityConfiguration.java
  core/java/iesi-rest-without-microservices/src/main/resources/application-iesi-repository.yml
Labels: enhancement
