Repository metadew/iesi, pull requests merged in 2020-06, with the labels that each got.

#149 Script Design - Expected Error - Invalid for incorrect/malformed input
  core/conf/application-metadata.yml
  core/java/iesi-core/src/main/java/io/metadew/iesi/common/configuration/Configuration.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/common/configuration/guard/GuardConfiguration.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/common/configuration/metadata/MetadataConfiguration.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/common/configuration/metadata/actiontypes/MetadataActionTypesConfiguration.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/common/configuration/metadata/componenttypes/MetadataComponentTypesConfiguration.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/common/configuration/metadata/connectiontypes/MetadataConnectionTypesConfiguration.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/common/configuration/metadata/objects/MetadataObjectsConfiguration.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/common/configuration/metadata/repository/MetadataRepositoryConfiguration.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/common/configuration/metadata/tables/MetadataTablesConfiguration.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/common/configuration/plugin/PluginConfiguration.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/connection/database/connection/SchemaDatabaseConnectionService.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/connection/database/oracle/OracleDatabaseConnectionService.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/connection/http/entity/json/ApplicationJsonHttpResponseEntityService.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/configuration/action/result/ActionResultOutputConfiguration.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/configuration/action/trace/ActionParameterTraceConfiguration.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/configuration/execution/script/ScriptExecutionRequestParameterConfiguration.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/configuration/mapping/MappingConfiguration.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/configuration/script/result/ScriptResultOutputConfiguration.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/configuration/type/ActionTypeConfiguration.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/operation/TypeConfigurationOperation.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/repository/MetadataRepository.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/repository/TraceMetadataRepository.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/service/action/ActionDesignTraceService.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/service/action/ActionParameterTraceService.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/service/action/ActionTraceService.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/service/metadata/MetadataFieldService.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/service/metadata/MetadataTableService.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/service/script/ScriptDesignTraceService.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/service/script/ScriptTraceService.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/data/DataCompareDataset.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/ActionExecution.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/data/DataInstructionRepository.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/data/text/TextSubstring.java
  core/java/iesi-core/src/main/resources/application-metadata.yml
  core/java/iesi-core/src/test/java/io/metadew/iesi/metadata/repository/RepositoryTestSetup.java
  core/java/iesi-core/src/test/java/io/metadew/iesi/script/execution/instruction/data/math/MultiplicationTest.java
  core/java/iesi-core/src/test/java/io/metadew/iesi/script/execution/instruction/data/text/TextSubstringTest.java
  core/java/iesi-core/src/test/resources/application-metadata.yml
Labels: bug

#148 action type: data.compareDataset - Mapping not found
  core/java/iesi-core/src/main/java/io/metadew/iesi/common/configuration/metadata/tables/MetadataTablesConfiguration.java
Labels: bug

#154 Dependency - SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"
  .github/ISSUE_TEMPLATE/documentation_request.md
  core/java/iesi-core/pom.xml
Labels: bug

#158 Double logging of script output causes primary key error
  core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/script/ScriptLogOutput.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/ExecutionControl.java
Labels: bug

#134 Addition to {{*number.between()}} function
  core/java/iesi-core/pom.xml
  core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/data/DataInstructionRepository.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/data/number/NumberBetween.java
  core/java/iesi-core/src/test/java/io/metadew/iesi/script/execution/instruction/data/number/NumberBetweenTest.java
Labels: enhancement

#142 add Lucie as a current commiter
  docs/pages/about.md
Labels: Documentation

#144 add Aurelien as current committer
  docs/pages/about.md
Labels: Documentation

#159 Clarification of QuickStart tutorials
  docs/pages/documentation.md
  docs/pages/tutorial/createfirstconnection.md
  docs/pages/tutorial/executescript.md
  docs/pages/tutorial/executescriptusingparameterlist.md
  docs/pages/tutorial/helloworldscript.md
  docs/pages/tutorial/loadconfiguration.md
  docs/pages/tutorial/tutorialenvironment.md
  docs/pages/tutorial/workingwithscriptversions.md
Labels: Documentation

#156 Expose endpoints to retrieve script result information
  core/java/iesi-core/src/main/java/io/metadew/iesi/connection/database/Database.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/connection/tools/SQLTools.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/configuration/script/result/ScriptResultConfiguration.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/definition/script/result/ScriptResult.java
  core/java/iesi-rest-without-microservices/pom.xml
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/dto/ScriptDtoModelAssembler.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/result/IScriptResultService.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/result/ScriptResultController.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/result/ScriptResultService.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/result/dto/ScriptResultDto.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/result/dto/ScriptResultDtoModelAssembler.java
  core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/builder/scriptresult/ScriptResultBuilder.java
  core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/script/result/ScriptResultControllerTest.java
  core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/script/result/ScriptResultServiceTest.java
Labels: enhancement
