Repository metadew/iesi, pull requests merged in 2021-03, with the labels that each got.

#294 clean up host operations
  core/java/iesi-core/src/main/java/io/metadew/iesi/connection/HostConnection.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/connection/operation/ConnectionOperation.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/connection/operation/FileTransferService.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/connection/tools/HostConnectionTools.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/cli/CliExecuteCommand.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/fho/FhoCreateFolder.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/fho/FhoDeleteFile.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/fho/FhoDeleteFolder.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/fho/FhoExecuteFileTransfer.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/fho/FhoFileExists.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/fho/FhoFolderExists.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/fwk/FwkExecuteSuite.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/wfa/WfaExecuteFilePing.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/wfa/WfaExecuteQueryPing.java
  core/java/iesi-core/src/main/resources/application-repository.yml
  core/java/iesi-core/src/main/resources/application.yml
Labels: enhancement

#296 sql.setRuntimeVariables does not use column labels for all database technologies
  core/java/iesi-core/pom.xml
  core/java/iesi-core/src/main/java/io/metadew/iesi/connection/database/sqlite/SqliteDatabaseService.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/configuration/connection/ConnectionConfiguration.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/sql/SqlSetRuntimeVariables.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/wfa/WfaExecuteFilePing.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/wfa/WfaExecuteQueryPing.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/ExecutionRuntime.java
  core/java/iesi-core/src/main/resources/application-connection-types.yml
  core/java/iesi-rest-without-microservices/pom.xml
  core/java/iesi-rest-without-microservices/src/main/resources/application-connection-types.yml
  core/java/iesi-rest-without-microservices/src/main/resources/application-iesi-repository.yml
  core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/dataset/DatasetDtoRepositoryTest.java
Labels: bug

#293 Transform openAPI into iesi from the cli
  core/assembly/file-assembly.conf
  core/bin/iesi-openapi.cmd
  core/bin/iesi-openapi.sh
  core/java/iesi-core/pom.xml
  core/java/iesi-core/src/main/java/io/metadew/iesi/connection/http/entity/json/ApplicationJsonHttpResponseEntityService.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/definition/component/ComponentJsonComponent.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/openapi/ComponentParser.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/openapi/ConnectionParser.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/openapi/OpenAPIGenerator.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/openapi/OpenAPILauncher.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/openapi/UnexpectedError.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/openapi/UnsuportedSecurityScheme.java
  core/java/iesi-core/src/main/resources/application.yml
  core/java/iesi-core/src/test/java/io/metadew/iesi/connection/http/entity/json/ApplicationJsonHttpResponseEntityServiceTest.java
  core/java/iesi-core/src/test/java/io/metadew/iesi/openapi/ComponentParserTest.java
  core/java/iesi-core/src/test/java/io/metadew/iesi/openapi/ConnectionParserTest.java
  core/java/iesi-core/src/test/java/io/metadew/iesi/openapi/OpenAPITest.java
Labels: enhancement

#284 Create new page - use cases
  docs/pages/Use Cases.md
Labels: documentation

#251 IESI Doc - Rework Home Page
  docs/index.md
Labels: documentation

#298 Add input location, output location and save to repository arguments to open-api command
  core/java/iesi-core/src/main/java/io/metadew/iesi/openapi/ComponentParser.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/openapi/ConnectionParser.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/openapi/OpenAPIGenerator.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/openapi/OpenAPILauncher.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/openapi/UnsuportedSecurityScheme.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/openapi/UnsupportedSecurityScheme.java
  core/java/iesi-core/src/main/resources/application.yml
  core/java/iesi-core/src/test/java/io/metadew/iesi/openapi/ComponentParserTest.java
  core/java/iesi-core/src/test/resources/application.yml
Labels: enhancement

#304 sql execute procedure does not resolve parameters
  core/java/iesi-core/src/main/java/io/metadew/iesi/connection/database/connection/DatabaseConnectionService.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/connection/database/db2/Db2DatabaseService.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/connection/database/oracle/OracleDatabaseConnectionService.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/connection/database/oracle/OracleDatabaseService.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/connection/database/postgresql/PostgresqlDatabaseService.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/datatypes/dataset/implementation/DatasetImplementationService.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/datatypes/dataset/implementation/IDatasetImplementationService.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/dataset/DatasetController.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/dataset/DatasetDtoRepository.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/dataset/DatasetDtoService.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/dataset/IDatasetDtoRepository.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/dataset/IDatasetDtoService.java
  core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/dataset/DatasetDtoRepositoryTest.java
  core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/dataset/DatasetsControllerSecurityTest.java
  core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/dataset/DatasetsControllerTest.java
Labels: bug

#300 Update the component parser to generate one component per operation
  core/java/iesi-core/src/main/java/io/metadew/iesi/openapi/ComponentParser.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/openapi/OpenAPILauncher.java
  core/java/iesi-core/src/test/java/io/metadew/iesi/openapi/ComponentParserTest.java
Labels: enhancement

#307 allow list to be reference name for eval.listContains
  .circleci/config.yml
  core/java/iesi-core/pom.xml
  core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/eval/EvalListContains.java
  core/java/iesi-rest-without-microservices/pom.xml
  core/java/iesi-rest-without-microservices/src/main/resources/application-iesi-repository.yml
  core/java/iesi-rest-without-microservices/src/main/resources/application-iesi.yml
Labels: bug

#305 Transform OpenAPI documentation through REST API
  core/conf/application-action-types.yml
  core/java/iesi-core/src/main/java/io/metadew/iesi/openapi/ComponentParser.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/openapi/ConnectionParser.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/openapi/OpenAPIGenerator.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/openapi/OpenAPILauncher.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/openapi/Parser.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/openapi/TransformResult.java
  core/java/iesi-rest-without-microservices/pom.xml
  core/java/iesi-rest-without-microservices/repository.db3
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/configuration/IesiConfiguration.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/openapi/IOpenAPIService.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/openapi/OpenAPIController.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/openapi/OpenAPIService.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/openapi/dto/TransformResultDto.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/openapi/dto/TransformResultDtoResourceAssembler.java
  core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/openapi/OpenAPIControllerTest.java
Labels: enhancement

#308 Throw exception from swagger parser through controller advice
  core/java/iesi-core/src/main/java/io/metadew/iesi/openapi/OpenAPIGenerator.java
  core/java/iesi-core/src/main/java/io/metadew/iesi/openapi/SwaggerParserException.java
  core/java/iesi-core/src/test/java/io/metadew/iesi/openapi/OpenAPIGeneratorTest.java
  core/java/iesi-core/src/test/java/io/metadew/iesi/openapi/OpenAPITest.java
  core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/error/CustomGlobalExceptionHandler.java
Labels: enhancement
